apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec: 
  selector:
    app: payment
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      name: payment
    spec:
      containers:
        - name: payment
          image: hakj/go-grpc-microservices-payment:1.0.0
          env:
            - name: PAYMENT_GRPC_PORT
              value: "9000"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: 
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
  name: payment
spec:
  ingressClassName: nginx
  rules:
    - host: ingress.payment.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 9000
