apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
spec: 
  selector:
    service: payment
  ports:
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
