apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  selector:
    app: inventory
  ports:
    - name: grpc
      port: 9001
      protocol: TCP
      targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
      name: inventory
    spec:
      containers:
        - name: inventory
          image: hakj/go-grpc-microservices-inventory:1.0.1
          env:
            - name: INVENTORY_GRPC_PORT
              value: "9001"
            - name: INVENTORY_DB_HOST
              value: "postgres"
